[package]
name = "ibm_5150"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
rand = "0.8.5"

[env]
RUST_MIN_STACK = 8388608
